
spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        provider:
          devops:
            issuer-uri: http://localhost:8080
        registration:
          devops:
            provider: devops
            client-id: devops
            client-secret: Qwerty@2024
            authorization-grant-type:
              - authorization_code
            scope: openid, profile
            redirect-uri: http://localhost:8081/login/oauth2/code/devops

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: webapp-bff
          uri: http://localhost:3000
          predicates:
            - Path=/**
        - id: identity
          uri: lb://identity
          predicates:
            - Path=/oauth2/**
          filters:
            - TokenRelay=
            - RewritePath=/oauth2/(?<segment>.*),/$\{segment}
server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"



client-security-matchers: >
  /login/**,
  /oauth2/**,
  /logout/**,
  /en/**,
  /auth/**,
  /error/**,
  /identity/**
  

client-permit-matchers: >
  /login/**,
  /oauth2/**,
  /en/**,
  /auth/**,
  /error/**,
  /identity/**

